### PR TITLE
100% done new portal update

### PR DESCRIPTION
**Pull request by lclc98**
Sorry had to get off because i need to pack going away tomorrow. The only thing it needs now is in blockatumportal.java line 187 or around there with the line(//Need if(^those blocks are there)). You have to check if its large bricks or sandstone. Also had to edit the block because it was the wrong shape. I might start it if i get more time tonight. 

Lclc98

### CODE REVIEW

**Comment by lclc98** [comment]
il finish it now

**Comment by lclc98** [comment]
Need to fixed the palace. I just forgot to change something il hopefully get it done soon

**Comment by lclc98** [comment]
replace: int height = par2Random.nextInt(10);
with: int height = par2Random.nextInt(64);

In the BiomeGenAtumDesert for generating the palace

**Comment by odininon** [comment]
Just some advice, you should always --amend PR commits and push -f. It looks nicer then multiple commits.

**Comment by lclc98** [comment]
I will redo the code hopefully this weekend

**Pull request closed without merging**
