### PR TITLE
Added Limestone Tools 

### PR DESCRIPTION
**Pull request by lclc98**
Also added Creative tab and paxel. (Images still need to be added). Added Glass recipe. Added dropped loot and stone soldiers immune to fire. If you want me to remove creative tab and paxel. Just tell me.

### CODE REVIEW

**Comment by Shadowclaimer** [comment]
What's Paxel?

**Comment by lclc98** [comment]
a pickaxe, axe and shovel combined

**Comment by lclc98** [comment]
thats my last commit for the day

**Comment by RebelKeithy** [comment]
there is one problem, the main branch is not supposed to show any changes after the contest closes, that's why I opened the post-modjam branch. Can you change the pull request to be for that branch?

**Comment by lclc98** [comment]
Ooh k, sorry new commit submitted with changed branch

**Pull request closed without merging**
